name: Test Rendering

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: make
          run: time make
        - name: render normal scene
          run: time ./render > render.log
        - name: render volumetric scene
          run: time ./volumerender > render.log